-- =====================================================================
-- SAKSHA — Migration 5: Notifications
--
-- Notifications are generated by database triggers, not by the app, so
-- they cannot be forgotten when a new screen calls an existing RPC.
-- Each row belongs to exactly one person and links to one record.
--
-- Deliberately NOT built (plan §99, §100): email, SMS, WhatsApp,
-- scheduled overdue jobs. Overdue is derived on the dashboard.
-- =====================================================================

create type public.notification_entity as enum
  ('client', 'task', 'document_request', 'workflow', 'message');

create table public.notifications (
  id           uuid primary key default gen_random_uuid(),
  firm_id      uuid not null references public.firms (id),
  user_id      uuid not null references public.users (id),
  title        text not null check (length(trim(title)) > 0),
  message      text not null check (length(trim(message)) > 0),
  entity_type  public.notification_entity not null,
  entity_id    uuid not null,
  read         boolean not null default false,
  created_at   timestamptz not null default now()
);
create index notifications_user_idx on public.notifications (user_id, read, created_at desc);

alter table public.notifications enable row level security;

-- You only ever see your own notifications.
create policy notifications_select on public.notifications for select to authenticated
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------
-- Helpers used by the triggers
-- ---------------------------------------------------------------------

-- Never notify someone about their own action, and never notify a user
-- who is inactive or still on a temporary password.
create function public.app_notify(
  p_user_id uuid, p_firm_id uuid, p_title text, p_message text,
  p_entity_type public.notification_entity, p_entity_id uuid, p_actor uuid default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if p_user_id is null or p_user_id = coalesce(p_actor, auth.uid()) then
    return;
  end if;
  if not exists (
    select 1 from users
    where id = p_user_id and firm_id = p_firm_id and is_active and not must_change_password
  ) then
    return;
  end if;

  insert into notifications (firm_id, user_id, title, message, entity_type, entity_id)
  values (p_firm_id, p_user_id, p_title, p_message, p_entity_type, p_entity_id);
end $$;

/** Everyone on the firm side who should hear about this client. */
create function public.app_firm_watchers(p_firm_id uuid, p_client_id uuid) returns setof uuid
language sql stable security definer set search_path = public as $$
  select id from users where firm_id = p_firm_id and role = 'ADMIN' and is_active
  union
  select cs.staff_id from client_staff cs
  join users u on u.id = cs.staff_id
  where cs.client_id = p_client_id and u.is_active
$$;

create function public.app_client_watchers(p_client_id uuid) returns setof uuid
language sql stable security definer set search_path = public as $$
  select cu.user_id from client_users cu
  join users u on u.id = cu.user_id
  where cu.client_id = p_client_id and u.is_active
$$;

-- ---------------------------------------------------------------------
-- Tasks: assignment and review
-- ---------------------------------------------------------------------
create function public.notify_task_change() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_client text; v_watcher uuid;
begin
  select name into v_client from clients where id = new.client_id;

  -- Newly assigned work, whether at creation or on reassignment.
  if new.assigned_to is not null
     and (tg_op = 'INSERT' or new.assigned_to is distinct from old.assigned_to) then
    perform public.app_notify(new.assigned_to, new.firm_id,
      'New task assigned to you',
      format('%s — %s (%s), due %s', v_client, new.title, new.period, to_char(new.due_date, 'DD Mon')),
      'task', new.id);
  end if;

  -- Work waiting for the CA's approval.
  if tg_op = 'UPDATE' and new.status = 'UNDER_REVIEW' and old.status is distinct from new.status then
    for v_watcher in select id from users where firm_id = new.firm_id and role = 'ADMIN' and is_active loop
      perform public.app_notify(v_watcher, new.firm_id,
        'Work ready for review',
        format('%s — %s is waiting for your approval', v_client, new.title),
        'task', new.id);
    end loop;
  end if;

  return null;
end $$;

create trigger tasks_notify
  after insert or update on public.tasks
  for each row execute function public.notify_task_change();

-- ---------------------------------------------------------------------
-- Document requests: asked for, uploaded, accepted, rejected
-- ---------------------------------------------------------------------
create function public.notify_document_request() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_client text; v_watcher uuid;
begin
  select name into v_client from clients where id = new.client_id;

  if tg_op = 'INSERT' then
    for v_watcher in select * from public.app_client_watchers(new.client_id) loop
      perform public.app_notify(v_watcher, new.firm_id,
        'Your CA needs a document',
        format('"%s" has been requested%s', new.title,
               case when new.due_date is null then '' else format(', by %s', to_char(new.due_date, 'DD Mon')) end),
        'document_request', new.id);
    end loop;
    return null;
  end if;

  if old.status is not distinct from new.status then
    return null;
  end if;

  if new.status = 'UPLOADED' then
    -- Tell the firm, not the person who just uploaded.
    for v_watcher in select * from public.app_firm_watchers(new.firm_id, new.client_id) loop
      perform public.app_notify(v_watcher, new.firm_id,
        'Document uploaded',
        format('%s sent "%s" for review', v_client, new.title),
        'document_request', new.id);
    end loop;
  elsif new.status in ('ACCEPTED', 'REJECTED') then
    for v_watcher in select * from public.app_client_watchers(new.client_id) loop
      perform public.app_notify(v_watcher, new.firm_id,
        case when new.status = 'ACCEPTED' then 'Document accepted' else 'Document needs to be sent again' end,
        case when new.status = 'ACCEPTED'
          then format('"%s" was accepted', new.title)
          else format('"%s" was not accepted — %s', new.title, coalesce(new.rejection_reason, 'see the request'))
        end,
        'document_request', new.id);
    end loop;
  end if;

  return null;
end $$;

create trigger document_requests_notify
  after insert or update on public.document_requests
  for each row execute function public.notify_document_request();

-- ---------------------------------------------------------------------
-- Messages: tell the other side
-- ---------------------------------------------------------------------
create function public.notify_message() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_role user_role; v_client text; v_watcher uuid; v_preview text;
begin
  select role into v_role from users where id = new.sender_id;
  select name into v_client from clients where id = new.client_id;
  v_preview := left(new.message, 120);

  if v_role = 'CLIENT' then
    for v_watcher in select * from public.app_firm_watchers(new.firm_id, new.client_id) loop
      perform public.app_notify(v_watcher, new.firm_id,
        format('Message from %s', v_client), v_preview, 'message', new.client_id, new.sender_id);
    end loop;
  else
    for v_watcher in select * from public.app_client_watchers(new.client_id) loop
      perform public.app_notify(v_watcher, new.firm_id,
        'Message from your CA firm', v_preview, 'message', new.client_id, new.sender_id);
    end loop;
  end if;

  return null;
end $$;

create trigger messages_notify
  after insert on public.messages
  for each row execute function public.notify_message();

-- ---------------------------------------------------------------------
-- Reading them
-- ---------------------------------------------------------------------
create function public.mark_notification_read(p_id uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  update notifications set read = true where id = p_id and user_id = auth.uid();
end $$;

create function public.mark_all_notifications_read() returns void
language plpgsql security definer set search_path = public as $$
begin
  update notifications set read = true where user_id = auth.uid() and not read;
end $$;

-- ---------------------------------------------------------------------
-- Function privileges
-- ---------------------------------------------------------------------
revoke execute on function
  public.app_notify(uuid, uuid, text, text, public.notification_entity, uuid, uuid),
  public.app_firm_watchers(uuid, uuid),
  public.app_client_watchers(uuid)
from public, anon, authenticated;

grant execute on function
  public.mark_notification_read(uuid),
  public.mark_all_notifications_read()
to authenticated;

revoke insert, update, delete on all tables in schema public from anon, authenticated;
